name: Instagram Downloader

on:
  workflow_dispatch:  # Trigger manually from the GitHub Actions UI

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instaloader

      - name: Create target directory
        run: |
          mkdir -p downloads/cutu_afrin  # Create the target directory for saving images

      - name: Download Instagram Images
        run: python download_instagram.py  # Run the script to download images

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4  # Use the latest stable version (v4)
        with:
          name: instagram-images
          path: downloads/cutu_afrin/  # Path to the folder where images are stored
